### ISSUE TITLE
specific columns

### ISSUE THREAD

**Issue by bitcodr** [johannesschobel/dingoquerymapper#19]
How can i get specific columns in DingoQueryMapperBuilder
 
code like below :

```      
        $orders = Order::whereNotNull('id');

        $qm = new DingoQueryMapperBuilder($request);

        return $qm->createFromBuilder($orders)->paginate()
```

**Comment by johannesschobel** [comment]
Please don't use the `DingoQueryMapperBuilder` directly, but rather use the `DingoQueryMapper`..

```php
$orders = Order::whereNotNull('id')->get();
$qm = new DingoQueryMapper($request);
$orders = $qm->createFromCollection($orders)->paginate();
```

Now you have a paginated collection of your orders.. If you want to filter by specific fields, you can call it via your `Request` like this: 
```GET /endpoint?field=value`

See the readme file for more details

**Comment by amiralii** [comment]
but i don't want to fetch all record and add query after that
createFromCollection  gets all records without query

**Comment by johannesschobel** [comment]
You can do your normal Eloquent-Queries as known from Laravel.. Then you pass it to the `DingoQueryMapper` which applies further features (like sorting, filtering, whatever)..

```php
$orders = Order::where(...)->where(...)->where(...)->get();
$qm = new DingoQueryMapper($request);
$orders = $qm->createFromCollection($orders)->paginate();
```

is completely valid..

**Comment by bitcodr** [comment]
But i don't want to fetch all record and add query after that
createFromCollection gets all records without query
I want to when adding a query on api like the blow ;
```
orders?name=x&lastname=y
```
query take just records with x name and y lastname

**Comment by johannesschobel** [comment]
I am very sorry, i really don't get what you mean / want..

**Comment by bitcodr** [comment]
But my apis query strings are dynamic
Cannot add static where on Eloquent-Queries for the dynamic queries
