### ISSUE TITLE
[proposal] support new laravel versions

### ISSUE THREAD

**Issue by asadhshujau** [johannesschobel/dingoquerymapper#4]
Hence this looks really simple to use

How about adding support for laravel 5.4 ? :)

**Comment by johannesschobel** [comment]
Can you make a PR? ;)

Am 11.04.2017 8:54 vorm. schrieb "Asadh Shujau" <notifications@github.com>:

**Comment by asadhshujau** [comment]
i cloned this locally and only changed compser.json laravel/framework version to 5.4.* and it works

**Comment by johannesschobel** [comment]
I thought so, as the package does not rely on L5.1 specific features...

I hope to add some new features in the future, like building the
collections from a Builder and so on.. if you have any suggestions, let me
know..

Cheers

Am 11.04.2017 10:06 vorm. schrieb "Asadh Shujau" <notifications@github.com>:

**Comment by johannesschobel** [comment]
should by resolved by #6
