### ISSUE TITLE
[help] limiting custom filter fields and mapping url parameters with database field names

### ISSUE THREAD

**Issue by asadhshujau** [johannesschobel/dingoquerymapper#5]
how do i limit from which fields i can filter
instead of typing database field name in the url..  i wanna map a parameter passed to url to actual database field name...
is this achievable ?
if so could you tell me how ?

**Comment by johannesschobel** [comment]
At the moment, all fields from the database are queryable.. if you have a
user model, you can call the route /users?firstname=a*&is_active=0 to get
all inactive users starting with "a"..

At the moment there is no "mapping" from query parameters to database
fields available, as this would result in a massive workload to set it up
for you as a developer..

However, you may need to exclude some query parameters from being parsed
(e.g., token). This is done in the config file..

Cheers

Am 11.04.2017 10:17 vorm. schrieb "Asadh Shujau" <notifications@github.com>:
