### ISSUE TITLE
PSR2 Standards

### ISSUE THREAD

**Issue by simondotwhite** [johannesschobel/dingoquerymapper#8]
Hey,

I've noticed this package isn't compatible with PSR2 code standards. 

I've gone ahead and forked to make it comparable.

**Comment by johannesschobel** [comment]
Hey @Sekonda .. wow, thanks a lot for your work / effort..
Only thing I am not sure about, is the additional dependecny in `composer.json`. Can you remove it? Then i would merge!

Thanks a lot for your time and effort!

**Comment by simondotwhite** [comment]
@johannesschobel It's needed for testing against standards through Travis CI, I believe. But if you want to remove Travis from the question then yes it could be removed.

**Comment by johannesschobel** [comment]
i think it would be better to remove it.. can you please adapt it? that would be very kind of you!
